export const SEARCH_ARTISTS_START = 'SEARCH_ARTISTS_START'
export const SEARCH_ARTISTS_DONE = 'SEARCH_ARTISTS_DONE'
export const SEARCH_ARTISTS_FAIL = 'SEARCH_ARTISTS_FAIL'

export const SEARCH_ARTIST_ALBUMS_START = 'SEARCH_ARTIST_ALBUMS_START'
export const SEARCH_ARTIST_ALBUMS_DONE = 'SEARCH_ARTIST_ALBUMS_DONE'
export const SEARCH_ARTIST_ALBUMS_FAIL = 'SEARCH_ARTIST_ALBUMS_FAIL'
