export const LIKED_ALBUMS_CHANGED = 'LIKED_ALBUMS_CHANGED'
export const LIKED_ALBUMS_LOAD_START = 'LIKED_ALBUMS_LOAD_START'
export const LIKED_ALBUMS_LOAD_DONE = 'LIKED_ALBUMS_LOAD_DONE'
export const LIKED_ALBUMS_LOAD_FAIL = 'LIKED_ALBUMS_LOAD_FAIL'
